### ISSUE TITLE
Documentation needs updating

### ISSUE THREAD

**Issue by DDevine** [tbranyen/backbone-boilerplate#276]
The documentation is really incomplete. It needs to more obvious how to use the tools/features of backbone-boilerplate and have a feature-complete running example that actually reflects the current feature-set.

 Just following the small set of example code within the project still leaves me with a lot of questions such as why doesn't the way LayoutManager looks to be used resemble the LayoutManager documentation (something es6 specific)? If there was an overview on how it was used in this project I would be able to understand what is going on.

I'd really like to know how Components are intended to be used. I have made pages that are Components (though navigation doesn't seem to work properly) and I think they could be used for making widgets/components within a page... But I don't really know without the documentation to give me an outline.

**Comment by tbranyen** [comment]
Hey @DDevine, as you've probably already guessed, this project isn't really maintained by me anymore. I left it in a usable state, but like you've correctly noticed, the documentation is lacking. Since this project is built with off-the-shelf modules that are all independently well documented, any documentation there would be effectively tutorial material. The components codeh is a tiny implementation over [LayoutManager](thttp://layoutmanager.org/) and should definitely be documented.

Anyways, I'm around in the [Gitter channel](https://gitter.im/tbranyen/backbone-boilerplate) if you have any questions or want to participate in maintaining.

**Comment by DDevine** [comment]
If I get a stage where I think I am "doing it right" I'll probably contribute. Good to know you're around. I'll keep my notes that I have been making and maybe they can be transformed into documentation - if I forget somebody can feel free to poke me in a few months.

**Comment by leehankyeol** [comment]
@DDevine Any updates?

**Comment by DDevine** [comment]
I never ended up getting a really solid feel for backbone-boilerplate. I made it work and hacked a fair bit of custom code however in the end the project was dropped. Maybe I was expecting too much from backbone-boilerplate? I think what I was really after was Marionette.

**Comment by tbranyen** [comment]
Closing out. Not gonna work on it myself.
